site_name: Spice Caps
nav:
  - Welcome: index.md
  - Our product : product.md
  - Recipes : recette.md
  - Avantages : avantage.md
  - Q&A : faq.md
  - Contact : contact.md

theme: material

extra_css:
  - extra.css
  - custom.css


