site_name: Spice Caps
nav:
  - Welcome: index.md
  - Our product : product.md
  - Recipes : recette.md
  - Subscription : avantage.md
  - Q&A : faq.md
  - Contact : contact.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  # Désactiver la table des matières
  toc:
    visible: false

extra_css:
  - extra.css
  - custom.css


